# models.py
from pydantic import BaseModel
from typing import Optional, List

class BaseResponse(BaseModel):
    """
    A base Pydantic model for all agent responses.

    Attributes:
        response_type (str): The type of the response.
        session_id (str): The session ID for the conversation.
        user_query (str): The user's query.
    """
    response_type: str
    session_id: str
    user_query: str

class RAGResponse(BaseResponse):
    """
    Pydantic model for a RAG agent response.

    Attributes:
        rag_content (str): The content generated by the RAG agent.
        sources (List[str]): A list of sources used to generate the response.
    """
    response_type: str = "rag"
    rag_content: str
    sources: List[str]

class SQLResponse(BaseResponse):
    """
    Pydantic model for a Text-to-SQL agent response.

    Attributes:
        summary (str): A summary of the SQL result.
        sql_query (str): The SQL query that was executed.
        tabular_result (str): The result of the query as a string-formatted table.
    """
    response_type: str = "sql"
    summary: str
    sql_query: str
    tabular_result: str

class MixedResponse(BaseResponse):
    """
    Pydantic model for a mixed-intent response.

    Attributes:
        synthesized_answer (str): The synthesized answer from both RAG and SQL results.
        rag_sources (List[str]): A list of sources used by the RAG agent.
        sql_query (str): The SQL query that was executed.
    """
    response_type: str = "mixed"
    synthesized_answer: str
    rag_sources: List[str]
    sql_query: str

class ErrorResponse(BaseResponse):
    """
    Pydantic model for an error response.

    Attributes:
        error_message (str): The error message.
        suggested_fix (Optional[str]): A suggested fix for the error.
    """
    response_type: str = "error"
    error_message: str
    suggested_fix: Optional[str] = None

class VoiceResponse(BaseResponse):
    """
    Pydantic model for a voice summarization response.

    Attributes:
        summary (str): The summary of the transcription.
        transcription (str): The full transcription of the audio file.
    """
    response_type: str = "voice"
    summary: str
    transcription: str
