# models.py
from pydantic import BaseModel
from typing import Optional, List

class BaseResponse(BaseModel):
    """
    A base Pydantic model for all agent responses. It includes common fields
    that should be present in every final output.
    """
    response_type: str
    session_id: str
    user_query: str

class RAGResponse(BaseResponse):
    """
    Pydantic model for a response generated by the RAG (Retrieval-Augmented Generation) agent.
    This model is used when the answer is sourced primarily from unstructured documents.
    """
    response_type: str = "rag"
    rag_content: str
    sources: List[str]  # To hold metadata about the source documents

class SQLResponse(BaseResponse):
    """
    Pydantic model for a response generated by the Text-to-SQL agent. This is used
    when the answer is sourced from a structured database query.
    """
    response_type: str = "sql"
    summary: str
    sql_query: str
    tabular_result: str  # The result as a string-formatted table

class MixedResponse(BaseResponse):
    """
    Pydantic model for a response from a mixed-intent query, where information
    from both RAG and SQL agents is synthesized into a single answer.
    """
    response_type: str = "mixed"
    synthesized_answer: str
    rag_sources: List[str]
    sql_query: str

class ErrorResponse(BaseResponse):
    """
    Pydantic model for an error response. This is used when the workflow
    fails and the error is handled by the LLM error agent.
    """
    response_type: str = "error"
    error_message: str
    suggested_fix: Optional[str] = None

class VoiceResponse(BaseResponse):
    """
    Pydantic model for a response from the Voice Summarization agent.
    """
    response_type: str = "voice"
    summary: str
    transcription: str
